### ISSUE TITLE
Friends backend (requires new API endpoints)

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#154]

**Comment by Hjortsberg** [comment]
Please clarify which new endpoints are needed.
Looking at the API i see 3 API calls related to ![Friends](https://roast.software/doc/restapi/#friends-for-user-add-new-friend). 

From what i recall from our latest conversation about friends is that in order to limit the scope, we would not "request/accept" friends. Instead we talked about the Twitter approach where we just add and unfriend users. 

I will assume that above is correct and make a small PR regarding this.

Best regards.

**Comment by Hjortsberg** [comment]
Looking at it a second time, isn't the API already correct regarding the "Twitter approach" ?

We can add, remove and fetch a users friends. Will not change anything as of this time.

Best regards.

**Comment by willeponken** [comment]
I should, also, have clarified that this ticket requires new tables in the database. Such as a `user_friends` table.

---
Regards, W. O. Wennerstroem.

**Comment by Hjortsberg** [comment]
Of course mr. With Out Wennerstroem. We will fix this.

Best regards.

**Comment by Hjortsberg** [comment]
fixed in PR: (fixed: #154)
