### ISSUE TITLE
Implement code editor for front end

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#62]
Blocked by #61

**Comment by Hjortsberg** [comment]
Preliminary solution is to embed Microsofts Monaco editor since it's made in TypeScript and seems really fluent to operate.

**Comment by Hjortsberg** [comment]
Since we're a little confused on how to implement this, I have collected a bunch of links that might help us.
https://blog.expo.io/building-a-code-editor-with-monaco-f84b3a06deaf
https://github.com/slupjs/monaco/blob/master/src/index.tsx
https://github.com/Microsoft/monaco-editor-samples/blob/master/browser-esm-webpack-small/index.js

**Comment by willeponken** [comment]
Yes, I'm very confused too. I'll go an solve #59 instead.

**Comment by Hjortsberg** [comment]
Wait, isn't this link exactly what we need ?! 
[Loading monaco with webpack and typescript](https://github.com/Microsoft/monaco-editor-webpack-plugin)

**Comment by willeponken** [comment]
Yes, very much that, yes.

Den mån 19 nov. 2018 21:59Philip Hjortsberg <notifications@github.com>
skrev:
